### ISSUE TITLE
npm ERROR

### ISSUE THREAD

**Issue by santi10** [marcoramilli/malcontrol#8]
Hi,

I'm trying make the installation but I've this issue with npm, such as:

root@CS-01:/opt/malcontrol# npm install
npm WARN package.json v8-profiler@4.0.1 No repository field.
/
> contextify@0.1.15 install /opt/malcontrol/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/malcontrol/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/malcontrol
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/malcontrol/npm-debug.log
npm ERR! not ok code 0
root@CS-01:/opt/malcontrol#

Can you help me, please?

Thx

**Comment by minias** [comment]
You need Python 2.7 version. 
Because the npm-gyp dependency is on it.
Please let me know if it's solved, this developer doesn't know.
